name: ci

on:
  workflow_dispatch:
    inputs:
      run_environment:
        description: 'Trigger run on provided environment'
        default: 'dev'
        required: true
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e-tests:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - uses: microsoft/playwright-github-action@v1
    - name: Install dependencies
      run: yarn
    - name: Execute Test in Headful mode
      run: xvfb-run --auto-servernum -- yarn test
  
  ## Upload Artifacts and Allure Deployment to repository github pages
    - name: Upload Artifacts
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: e2e-artifacts
        path: |
         test-results
         allure-results
        retention-days: 7       
    
    - name: Get Allure history
      uses: actions/checkout@v2
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages
    
    - name: Test marketplace action
      uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
        allure_results: allure-results
        gh_pages: gh-pages
        allure_report: allure-report
        allure_history: allure-history
        keep_reports: 10

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history
